language: php
php:
  - 5.3
  - 5.4

before_install:
  - cd ..; git clone https://github.com/owncloud/appframework; cd news

script:
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get update
  - sudo apt-get -y install nodejs phantomjs
  - make unit-tests && make javascript-tests
