language: php
php:
    - 5.4
    - 5.5
    - 5.6

env:
    - DB=sqlite
    - DB=postgresql
    - DB=mysql

before_install:
    # get a newer node.js version
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sudo add-apt-repository -y ppa:chris-lea/node.js  # ubuntu 12.04 only
    - sudo apt-get update
    - sudo apt-get -o DPkg::Options::="--force-confold" -y upgrade
    - npm install -g npm@latest

install:
    - cd ..
    - sudo apt-get -y install nodejs python3-jinja2 python3-setuptools apache2 libapache2-mod-fastcgi firefox chromium-browser curl
    - export CHROME_BIN=/usr/bin/chromium-browser
    - sudo easy_install3 pip  # ubuntu 12.04 only
    - sudo pip3 install ocdev
    # clone core
    - ocdev setup core --dir owncloud --branch stable7
    - mv news owncloud/apps/

before_script:
    # set up databases and users for postgres and mysql
    - createuser -U travis -s oc_autotest
    - mysql -e 'create database oc_autotest;'
    - mysql -u root -e "CREATE USER 'oc_autotest'@'localhost';"
    - mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"
    # set up php under apache
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    - sudo cp -f owncloud/apps/news/tests/travis/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    # fill owncloud with default configs and enable news
    - cd owncloud
    - mkdir apps2
    - sudo chown -R www-data:www-data data/
    - ocdev ci $DB
    - php -f console.php app:enable news
    - sudo chown -R travis:travis data/
    - cd apps/news/js
    # install test deps
    - npm install --deps # npm install needs to run before sudo npm install because otherwise it fails because a tmp file exists in the home dir
    - sudo npm -g install grunt-cli protractor
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    # unit tests
    - grunt php-unit
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - grunt js-unit
    # integration tests
    - cd ..
    - phpunit -c phpunit.integration.xml
    - cd js
    # acceptance tests
    - webdriver-manager update
    - sudo chown -R www-data:www-data ../../../data/
    #- grunt acceptance --verbose
    # debug section to check what went wrong
    - curl http://admin:admin@localhost/owncloud/index.php
    - curl http://admin:admin@localhost/owncloud/index.php/apps/news/
    - sudo cat ../../../data/owncloud.log

addons:
    postgresql: "9.3"
