language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
    - DB=sqlite
    - DB=pgsql
    - DB=mysql

before_install:
    # get a newer node.js version
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sudo add-apt-repository -y ppa:chris-lea/node.js  # ubuntu 12.04 only
    - sudo apt-get update
    - sudo apt-get install -o DPkg::Options::="--force-confold" -y libxml2 libxml2-dev libxml2-utils
    - npm install -g npm@latest

install:
    - cd ..
    - sudo apt-get -y install nodejs python3-jinja2 python3-setuptools apache2 libapache2-mod-fastcgi firefox chromium-browser curl
    - export CHROME_BIN=/usr/bin/chromium-browser
    - sudo easy_install3 requests
    - sudo easy_install3 ocdev
    # clone core
    - ocdev setup core --dir owncloud --branch master --no-history
    - mv news owncloud/apps/

before_script:
    - phpenv config-add owncloud/apps/news/tests/travis/php.ini
    # set up databases and users for postgres and mysql
    - createuser -U travis -s oc_autotest
    - mysql -e 'create database oc_autotest;'
    - mysql -u root -e "CREATE USER 'oc_autotest'@'localhost';"
    - mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"
    # set up php under apache
    - bash owncloud/apps/news/tests/travis/travis-ci-apache.sh
    # fill owncloud with default configs and enable news
    - cd owncloud
    - mkdir apps2
    - mkdir data
    - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass
    - ./occ app:enable news
    - cd apps/news/js
    # install test deps
    - npm install --deps # npm install needs to run before sudo npm install because otherwise it fails because a tmp file exists in the home dir
    - sudo npm -g install grunt-cli protractor
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    # unit tests
    - grunt php-unit
    #- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - grunt js-unit
    # integration tests
    - grunt php-integration
    # acceptance tests
    - webdriver-manager update
    - sudo chown -R www-data:www-data ../../../data
    - sudo chmod -R a+rwx ../../../data
    #- grunt acceptance --verbose
    # debug section to check what went wrong
    - curl http://admin:admin@localhost/owncloud/index.php
    - curl http://admin:admin@localhost/owncloud/index.php/apps/news/
    - sudo cat ../../../data/owncloud.log

addons:
    postgresql: "9.3"

