site_name: Nextcloud News App
site_url: https://nextcloud.github.io/news/
site_description: Documentation for the Nextcloud News App
site_author: Nextcloud News Team
repo_url: https://github.com/nextcloud/news
edit_uri: blob/master/documentation/

nav:
  - index.md
  - install.md
  - clients.md
  - admin.md
  - developer.md
  - faq.md
  - Features:
    - Custom CSS: features/customCSS.md
    - Plugins: features/plugins.md
    - Themes: features/themes.md
  - REST API:
    - API v1.2: api/api-v1-2.md
    - API v1.3: api/api-v1-3.md
    - API v2: api/api-v2.md
  - maintenance.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  font: false
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - navigation.sections

markdown_extensions:
  - admonition

# extra:
#   version:
#     provider: mike
