site_name: Nextcloud News App
site_url: https://nextcloud.github.io/news/
site_description: Documentation for the Nextcloud News App
site_author: Nextcloud News Team
repo_url: https://github.com/nextcloud/news
edit_uri: blob/master/documentation/

nav:
  - index.md
  - install.md
  - clients.md
  - admin.md
  - developer.md
  - troubleshooting.md
  - Features:
    - Integration: features/integration.md
    - Custom CSS: features/customCSS.md
    - Plugins: features/plugins.md
    - Themes: features/themes.md
  - REST API:
    - API v1.2: api/api-v1-2.md
    - API v1.3: api/api-v1-3.md
    - API v2: api/api-v2.md
  - maintenance.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  font: false
  palette:
   - media: "(prefers-color-scheme: light)"
     scheme: default
     accent: indigo
     primary: indigo
     toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: slate
     primary: indigo
     accent: indigo
     toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: "code-line"
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# extra:
#   version:
#     provider: mike
