name: Static analysis
on:
  pull_request

permissions: {}
jobs:
  static-phpstan-analysis:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    strategy:
      matrix:
        php-versions: ['8.2', '8.3' ]
        nextcloud: [ 'stable32' ]
        database: [ 'sqlite' ]
        include:
          - php-versions: 8.3
            nextcloud: pre-release
            database: sqlite
            experimental: true
          - php-versions: 8.4
            nextcloud: pre-release
            database: sqlite
            experimental: true
    name: "phpstan: Nextcloud ${{ matrix.nextcloud }} with ${{ matrix.php-versions }}"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up php
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo_sqlite,pdo_mysql,pdo_pgsql,gd,zip
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up server non MySQL
        uses: SMillerDev/nextcloud-actions/setup-nextcloud@7665802e389e40d21b49877c3728bacca324d6e0 #latest
        with:
          cron: true
          version: ${{ matrix.nextcloud }}
          database-type: ${{ matrix.database }}

      - name: Build app
        run: make composer

      - name: Configure server with app
        uses: SMillerDev/nextcloud-actions/setup-nextcloud-app@7665802e389e40d21b49877c3728bacca324d6e0 #latest
        with:
          app: 'news'
          check-code: false
          force: true

      - name: Prep code scanning
        working-directory: ../server/apps/news
        run: make php-test-dependencies

      - name: PHPCS
        working-directory: ../server/apps/news
        run: make phpcs

      - name: PHPStan
        working-directory: ../server/apps/news
        run: make phpstan
